[pytest]
xfail_strict = true
addopts = --cov-report term-missing --cov librosa --cov-report=xml --mpl --mpl-baseline-path=tests/baseline_images/test_display
testpaths = tests
filterwarnings =
	ignore::DeprecationWarning:audioread.*
	ignore::DeprecationWarning:resampy.*
norecursedirs =
	tests/results
	Benchmarks/results
	target
	.git
	.pytest_cache
	__pycache__
python_files = test_*.py
